### ISSUE TITLE
xmpp-client won't compile on Mac OS X 10.8.2

### ISSUE THREAD

**Issue by nueh** [agl/xmpp-client#11]
```
src/github.com/agl/xmpp-client/ui.go:141: undefined: terminal.MakeRaw
src/github.com/agl/xmpp-client/ui.go:145: undefined: terminal.Restore
src/github.com/agl/xmpp-client/ui.go:147: undefined: terminal.GetSize
```

It obviously has something to do with code.google.com/p/go.crypto/ssh/terminal, termios, syscall, etc. Unfortunately that's way beyond my knowledge.
Maybe some parts of https://github.com/nsf/termbox-go could be helpful? E.g. `syscalls_darwin_amd64.go`
